"""empty message

Revision ID: 77460f720682
Revises: 42297d9d0a54
Create Date: 2024-07-09 13:11:09.090226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77460f720682'
down_revision = '42297d9d0a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('logo')

    # ### end Alembic commands ###
